-- Square Inch - full schema, both migrations in order.
-- Generated for one-shot pasting into the Supabase SQL editor.
-- Source of truth remains supabase/migrations/*.sql - do not edit this file.


-- ===================================================================
-- 20260916120000_init.sql
-- ===================================================================

-- ===========================================================================
-- Square Inch on Supabase.
--
-- Run this whole file in the SQL editor of a new project, then put the project
-- URL and the anon key in .env.
--
-- The shape of the security here is worth reading before you change anything:
--
--   listings, spots, profiles   the browser reads and writes directly, under
--                               Row Level Security. Owners edit their own.
--   bids                        the browser may READ but never write. Only the
--                               service role can insert, because a bid decides
--                               a price and takes money, and the browser is
--                               not allowed to do either.
--   messages                    write as yourself, read if you can see the
--                               listing.
-- ===========================================================================

-- --------------------------------------------------------------- people
create table if not exists profiles (
  id            uuid primary key references auth.users on delete cascade,
  role          text not null check (role in ('client','brand')),
  display_name  text not null check (char_length(display_name) between 1 and 80),
  brand         text check (char_length(brand) <= 60),
  logo_url      text,
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------------------- listings
create table if not exists listings (
  id           uuid primary key default gen_random_uuid(),
  owner        uuid not null references profiles(id) on delete cascade,
  names        text not null default '',
  garment      text not null default 'gown' check (garment in ('gown','suit')),

  -- the page's own copy
  headline     text check (char_length(headline) <= 90),
  tagline      text check (char_length(tagline) <= 200),
  about        text check (char_length(about) <= 600),
  instagram    text check (char_length(instagram) <= 40),
  twitter      text check (char_length(twitter) <= 40),

  -- the day
  city         text,
  event_date   date,
  venue        text,
  venue_type   text,
  invited      int not null default 0 check (invited >= 0),
  confirmed    int not null default 0 check (confirmed >= 0),
  shooters     text,
  reach        int not null default 0 check (reach >= 0),
  hashtag      text,
  press        text,
  livestream   boolean not null default false,

  -- the market
  goal         numeric(12,2) not null default 0 check (goal >= 0),
  fee_percent  numeric(5,2) not null default 8 check (fee_percent between 0 and 30),
  currency     text not null default 'usd',
  closes_at    timestamptz,
  is_open      boolean not null default false,

  -- front and back, uploaded by the owner into the `garments` bucket
  photo_front  text,
  photo_back   text,

  created_at   timestamptz not null default now()
);
create index if not exists listings_open_idx on listings (is_open, closes_at);
create index if not exists listings_owner_idx on listings (owner);

-- ---------------------------------------------------------------- spots
-- Position is stored in PERCENTAGES of the photograph, never in pixels, so a
-- spot laid out on a laptop lands in the same place on a phone.
create table if not exists spots (
  id          uuid primary key default gen_random_uuid(),
  listing_id  uuid not null references listings(id) on delete cascade,
  side        text not null check (side in ('front','back')),
  n           int  not null check (n > 0),
  name        text not null check (char_length(name) between 1 and 40),
  badge       text check (char_length(badge) <= 10),
  blurb       text check (char_length(blurb) <= 240),
  x           numeric(6,2) not null check (x between 0 and 100),
  y           numeric(6,2) not null check (y between 0 and 100),
  w           numeric(6,2) not null check (w > 0 and w <= 100),
  h           numeric(6,2) not null check (h > 0 and h <= 100),
  floor       numeric(10,2) not null default 100 check (floor >= 1),
  -- set only when anti-snipe has pushed this one spot past the listing's close
  closes_at   timestamptz,
  created_at  timestamptz not null default now()
);
create index if not exists spots_listing_idx on spots (listing_id, side, n);

-- ----------------------------------------------------------------- bids
-- One row per authorised bid. `max_amount` is the bidder's ceiling;
-- `settled_amount` is what they were actually charged, which is usually less.
--
--   held      the card is authorised, the money is not taken
--   released  outbid or the goal was missed - the authorisation was cancelled
--   captured  they held the spot at close and have been charged
create table if not exists bids (
  id                     uuid primary key default gen_random_uuid(),
  listing_id             uuid not null references listings(id) on delete cascade,
  spot_id                uuid not null references spots(id) on delete cascade,
  bidder                 uuid not null references profiles(id) on delete cascade,
  brand                  text not null check (char_length(brand) between 1 and 60),
  logo_url               text,
  max_amount             numeric(12,2) not null check (max_amount > 0),
  settled_amount         numeric(12,2),
  status                 text not null default 'held' check (status in ('held','released','captured')),
  withdrawn              boolean not null default false,
  stripe_session         text unique,
  stripe_payment_intent  text,
  released_at            timestamptz,
  settled_at             timestamptz,
  created_at             timestamptz not null default now()
);
create index if not exists bids_spot_idx on bids (spot_id, status);
create index if not exists bids_listing_idx on bids (listing_id, created_at desc);

-- -------------------------------------------------------------- messages
create table if not exists messages (
  id            uuid primary key default gen_random_uuid(),
  listing_id    uuid not null references listings(id) on delete cascade,
  author        uuid not null references profiles(id) on delete cascade,
  display_name  text not null,
  role          text not null check (role in ('client','brand')),
  body          text not null check (char_length(body) between 1 and 400),
  created_at    timestamptz not null default now()
);
create index if not exists messages_listing_idx on messages (listing_id, created_at);

-- ===========================================================================
-- Row Level Security
-- ===========================================================================
alter table profiles enable row level security;
alter table listings enable row level security;
alter table spots    enable row level security;
alter table bids     enable row level security;
alter table messages enable row level security;

-- profiles: public to read (brand names appear on the wall), yours to write
drop policy if exists "profiles readable"   on profiles;
drop policy if exists "own profile insert"  on profiles;
drop policy if exists "own profile update"  on profiles;
create policy "profiles readable"  on profiles for select using (true);
create policy "own profile insert" on profiles for insert with check (auth.uid() = id);
create policy "own profile update" on profiles for update using  (auth.uid() = id)
                                                     with check  (auth.uid() = id);

-- listings: anyone may read; only the owner may write, and only as themselves
drop policy if exists "listings readable"     on listings;
drop policy if exists "owner inserts listing" on listings;
drop policy if exists "owner edits listing"   on listings;
drop policy if exists "owner deletes listing" on listings;
create policy "listings readable"     on listings for select using (true);
create policy "owner inserts listing" on listings for insert with check (auth.uid() = owner);
create policy "owner edits listing"   on listings for update using  (auth.uid() = owner)
                                                        with check  (auth.uid() = owner);
create policy "owner deletes listing" on listings for delete using  (auth.uid() = owner);

-- spots: readable by all, writable only by whoever owns the listing they hang off
drop policy if exists "spots readable"     on spots;
drop policy if exists "owner writes spots" on spots;
drop policy if exists "owner edits spots"  on spots;
drop policy if exists "owner drops spots"  on spots;
create policy "spots readable" on spots for select using (true);
create policy "owner writes spots" on spots for insert
  with check (exists (select 1 from listings l where l.id = listing_id and l.owner = auth.uid()));
create policy "owner edits spots" on spots for update
  using      (exists (select 1 from listings l where l.id = listing_id and l.owner = auth.uid()))
  with check (exists (select 1 from listings l where l.id = listing_id and l.owner = auth.uid()));
create policy "owner drops spots" on spots for delete
  using      (exists (select 1 from listings l where l.id = listing_id and l.owner = auth.uid()));

-- bids: the market is meant to be visible, so everyone reads.
-- NOBODY writes. There is deliberately no insert, update or delete policy:
-- with RLS on and no policy, every write from the browser is refused. Bids are
-- created by the server with the service role key, after it has revalidated
-- the price and taken an authorisation from Stripe.
drop policy if exists "bids readable" on bids;
create policy "bids readable" on bids for select using (true);

-- messages: read if you can see the listing, write only as yourself
drop policy if exists "messages readable"      on messages;
drop policy if exists "author inserts message" on messages;
create policy "messages readable"      on messages for select using (true);
create policy "author inserts message" on messages for insert with check (auth.uid() = author);

-- ===========================================================================
-- Storage
-- ===========================================================================
insert into storage.buckets (id, name, public)
  values ('garments','garments', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
  values ('logos','logos', true) on conflict (id) do nothing;

-- Anyone may look; you may only write inside a folder you are entitled to.
-- Garment photographs live at  <listing_id>/front.jpg
-- Brand marks live at          <user_id>/logo.png
drop policy if exists "garment photos readable" on storage.objects;
drop policy if exists "owner uploads garment"   on storage.objects;
drop policy if exists "owner replaces garment"  on storage.objects;
drop policy if exists "owner deletes garment"   on storage.objects;
drop policy if exists "logos readable"          on storage.objects;
drop policy if exists "own logo write"          on storage.objects;
drop policy if exists "own logo update"         on storage.objects;

create policy "garment photos readable" on storage.objects for select
  using (bucket_id = 'garments');

create policy "owner uploads garment" on storage.objects for insert to authenticated
  with check (bucket_id = 'garments' and exists (
    select 1 from listings l
    where l.owner = auth.uid() and l.id::text = (storage.foldername(name))[1]));

create policy "owner replaces garment" on storage.objects for update to authenticated
  using (bucket_id = 'garments' and exists (
    select 1 from listings l
    where l.owner = auth.uid() and l.id::text = (storage.foldername(name))[1]));

create policy "owner deletes garment" on storage.objects for delete to authenticated
  using (bucket_id = 'garments' and exists (
    select 1 from listings l
    where l.owner = auth.uid() and l.id::text = (storage.foldername(name))[1]));

create policy "logos readable" on storage.objects for select
  using (bucket_id = 'logos');

create policy "own logo write" on storage.objects for insert to authenticated
  with check (bucket_id = 'logos' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "own logo update" on storage.objects for update to authenticated
  using (bucket_id = 'logos' and auth.uid()::text = (storage.foldername(name))[1]);

-- ===========================================================================
-- Realtime - this is what makes bidding and chat live without polling
-- ===========================================================================
do $$
begin
  alter publication supabase_realtime add table bids;
exception when duplicate_object then null; end $$;
do $$
begin
  alter publication supabase_realtime add table spots;
exception when duplicate_object then null; end $$;
do $$
begin
  alter publication supabase_realtime add table messages;
exception when duplicate_object then null; end $$;
do $$
begin
  alter publication supabase_realtime add table listings;
exception when duplicate_object then null; end $$;

-- ===========================================================================
-- A profile row for every new sign-up, created by the database rather than by
-- the client, so an account can never exist without one.
-- ===========================================================================
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, role, display_name, brand)
  values (
    new.id,
    -- self-selected, but clamped: anything other than 'client' becomes 'brand'
    case when new.raw_user_meta_data->>'role' = 'client' then 'client' else 'brand' end,
    coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''), split_part(new.email, '@', 1)),
    nullif(trim(new.raw_user_meta_data->>'brand'), '')
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===========================================================================
-- Your role is fixed when the account is created.
-- ===========================================================================
create or replace function public.freeze_profile_role()
returns trigger language plpgsql as $$
begin
  if new.role is distinct from old.role then
    raise exception 'role cannot be changed after sign-up';
  end if;
  return new;
end $$;

drop trigger if exists profiles_role_is_immutable on public.profiles;
create trigger profiles_role_is_immutable
  before update on public.profiles
  for each row execute function public.freeze_profile_role();

-- ===================================================================
-- 20260916140000_seal_the_market.sql
-- ===================================================================

-- ===========================================================================
-- Seal the market.
--
-- The first migration left `bids` world-readable, which quietly broke the
-- promise the product is built on. `bids.max_amount` is a brand's secret
-- ceiling; with `using (true)` anyone holding the anon key - which the page
-- publishes, by design - could read every rival's maximum and bid one unit
-- over it. Proxy bidding only works if the ceiling is private.
--
-- The page still needs a price to draw, so the settled figures move onto
-- `spots`, written by the server after each bid. The browser reads those and
-- never needs anyone's maximum again.
-- ===========================================================================

-- ------------------------------------------------ what the page may know
alter table spots add column if not exists price        numeric(12,2);
alter table spots add column if not exists holder       uuid references profiles(id) on delete set null;
alter table spots add column if not exists holder_brand text;
alter table spots add column if not exists holder_logo  text;
alter table spots add column if not exists bid_count    int not null default 0;

comment on column spots.price is
  'The settled price, written by the server after every bid. Public. Never derived in the browser.';
comment on column spots.holder is
  'Who currently holds the spot. The amount they were willing to pay is not public.';

-- Back-fill so a spot with no bids reads as its floor rather than as null.
update spots set price = floor where price is null;

-- --------------------------------------------------------- bids, sealed
drop policy if exists "bids readable"     on bids;
drop policy if exists "own bids readable" on bids;

-- You see your own bids. A publisher sees the bids on their own garment,
-- because they are the one being paid. Nobody else sees anything: no
-- maximums, no Stripe identifiers, no bidder ids.
create policy "own bids readable" on bids for select using (
  auth.uid() = bidder
  or exists (select 1 from listings l where l.id = bids.listing_id and l.owner = auth.uid())
);

-- Still no insert/update/delete policy anywhere. With RLS on and no policy,
-- every write from a browser is refused; only the service role writes bids.

-- One live authorisation per bidder per spot. Raising your own maximum is
-- allowed, but the older row must be released first - two `held` rows for one
-- bidder meant settlement captured both and charged them twice.
create unique index if not exists bids_one_hold_per_bidder_per_spot
  on bids (spot_id, bidder) where status = 'held' and withdrawn = false;

-- ------------------------------------------------------ messages, honest
-- `display_name` and `role` were free text from the client, so a brand could
-- insert {display_name:'Maya', role:'client'} and impersonate the publisher.
-- They must now match the profile of whoever is writing.
drop policy if exists "author inserts message" on messages;
create policy "author inserts message" on messages for insert with check (
  auth.uid() = author
  and role = (select p.role from profiles p where p.id = auth.uid())
  and display_name = (select coalesce(p.brand, p.display_name) from profiles p where p.id = auth.uid())
);

-- ------------------------------------------------- listings, role-gated
-- Only a publisher account may open a listing. Without this the client/brand
-- split lived only in the UI, and any signed-in user could create listings
-- straight through PostgREST.
drop policy if exists "owner inserts listing" on listings;
create policy "owner inserts listing" on listings for insert with check (
  auth.uid() = owner
  and exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'client')
);

-- ---------------------------------------------------- storage, bounded
-- The upload policies checked the folder but not the contents, and the size
-- and type limits lived in the browser - which an attacker simply skips by
-- calling the storage API directly. Both buckets are public, so without this
-- an account is free hosting for anything at all on a *.supabase.co domain.
update storage.buckets
   set file_size_limit = 8388608,
       allowed_mime_types = array['image/jpeg','image/png','image/webp']
 where id = 'garments';

update storage.buckets
   set file_size_limit = 2097152,
       allowed_mime_types = array['image/jpeg','image/png','image/webp','image/svg+xml']
 where id = 'logos';

-- Tighten the filename too, so nothing that is not an image can be stored
-- even if a mime type is spoofed.
drop policy if exists "owner uploads garment" on storage.objects;
create policy "owner uploads garment" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'garments'
    and storage.extension(name) = any (array['jpg','jpeg','png','webp'])
    and exists (
      select 1 from listings l
      where l.owner = auth.uid() and l.id::text = (storage.foldername(name))[1])
  );

drop policy if exists "own logo write" on storage.objects;
create policy "own logo write" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'logos'
    and storage.extension(name) = any (array['jpg','jpeg','png','webp','svg'])
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- A brand replacing its own mark needs to be able to remove the old object.
drop policy if exists "own logo delete" on storage.objects;
create policy "own logo delete" on storage.objects for delete to authenticated
  using (bucket_id = 'logos' and auth.uid()::text = (storage.foldername(name))[1]);

-- --------------------------------------------------------------- realtime
-- The page now watches spots for price changes rather than watching bids,
-- which it can no longer read.
do $$
begin
  alter publication supabase_realtime add table spots;
exception when duplicate_object then null; end $$;
